In [30]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [31]:
df=pd.read_csv('seasonal_final.csv')
df.head()

xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0            1              0                          0   
1            3              2                          0   
2            1              1                          0   
3            1              1                          0   
4            2              1                          0   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                     0                     0                      0   
1                     1                     0                      1   
2                     1                     0                      0   
3                     1                     0                      1   
4                     1                     0                      1   

   behavioral_outside_home  behavioral_touch_face  chronic_med_condition  \
0                        1                      1                      0   
1                        1                      1                      0   
2                        0                      0                      1   
3                        0                      0                      1   
4                        0                      1                      0   

   child_under_6_months  health_worker  opinion_seas_vacc_effective  \
0                     0              0                            2   
1                     0              0                            4   
2                     0              0                            4   
3                     0              0                            5   
4                     0              0                            3   

   opinion_seas_risk  opinion_seas_sick_from_vacc  age_group  race  sex  \
0                  1                            2          4     3    1   
1                  2                            4          2     3    0   
2                  1                            2          1     3    0   
3                  4                            1          5     3    1   
4                  1                            4          3     3    1   

   household_adults  household_children  seasonal_vaccine  
0                 0                   0                 0  
1                 0                   0                 1  
2                 2                   0                 0  
3                 0                   0                 1  
4                 1                   0                 0

In [32]:
df.shape

(24938, 20)

In [9]:
X=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)
X_train, X_dev, y_train, y_dev = train_test_split(X_train, y_train, test_size=0.2, random_state=1234)

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

models = {
    'Logistic Regression': LogisticRegression(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Support Vector Classifier': SVC(probability=True),  # Enable probability estimates
    'Gaussian Naive Bayes': GaussianNB()
}

for name, model in models.items():
    print(f"Training {name}...")
    model.fit(X_train, y_train)
    
    # Predict probabilities for test set
    y_pred_proba = model.predict_proba(X_dev)[:, 1]  # Probabilities of the positive class
    
    # Example evaluation (replace with your own metrics)
    print(f"\n{name} Classification Report:")
    y_pred = model.predict(X_dev)
    print(classification_report(y_dev, y_pred))
    
    # Example of other metrics (accuracy, confusion matrix)
    print(f"{name} Accuracy: {accuracy_score(y_dev, y_pred)}")
    print(f"{name} Confusion Matrix:")
    print(confusion_matrix(y_dev, y_pred))

    print("\n---------------------------------------\n")

Training Logistic Regression...

Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.79      0.78      2113
           1       0.75      0.73      0.74      1877

    accuracy                           0.76      3990
   macro avg       0.76      0.76      0.76      3990
weighted avg       0.76      0.76      0.76      3990

Logistic Regression Accuracy: 0.7598997493734336
Logistic Regression Confusion Matrix:
[[1665  448]
 [ 510 1367]]

---------------------------------------

Training K-Nearest Neighbors...

K-Nearest Neighbors Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.78      0.76      2113
           1       0.74      0.70      0.72      1877

    accuracy                           0.74      3990
   macro avg       0.74      0.74      0.74      3990
weighted avg       0.74      0.74      0.74      3990

K-Nearest Neighbors Accuracy: 0.740601

In [14]:
models = {
    'Logistic Regression': LogisticRegression(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Support Vector Classifier': SVC(probability=True),  # Enable probability estimates
    'Gaussian Naive Bayes': GaussianNB()
}

for name, model in models.items():
    print(f"Training {name}...")
    model.fit(X_train, y_train)
    
    # Predict probabilities for test set
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # Probabilities of the positive class
    
    # Example evaluation (replace with your own metrics)
    print(f"\n{name} Classification Report:")
    y_pred = model.predict(X_test)
    print(classification_report(y_test, y_pred))
    
    # Example of other metrics (accuracy, confusion matrix)
    print(f"{name} Accuracy: {accuracy_score(y_test, y_pred)}")
    print(f"{name} Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    print("\n---------------------------------------\n")

Training Logistic Regression...

Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.78      0.78      2683
           1       0.74      0.74      0.74      2305

    accuracy                           0.76      4988
   macro avg       0.76      0.76      0.76      4988
weighted avg       0.76      0.76      0.76      4988

Logistic Regression Accuracy: 0.7610264635124299
Logistic Regression Confusion Matrix:
[[2099  584]
 [ 608 1697]]

---------------------------------------

Training K-Nearest Neighbors...

K-Nearest Neighbors Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.74      0.74      2683
           1       0.70      0.70      0.70      2305

    accuracy                           0.72      4988
   macro avg       0.72      0.72      0.72      4988
weighted avg       0.72      0.72      0.72      4988

K-Nearest Neighbors Accuracy: 0.724338

In [15]:
X.columns

Index(['xyz_concern', 'xyz_knowledge', 'behavioral_antiviral_meds',
       'behavioral_avoidance', 'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_outside_home', 'behavioral_touch_face',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'opinion_seas_vacc_effective', 'opinion_seas_risk',
       'opinion_seas_sick_from_vacc', 'age_group', 'race', 'sex',
       'household_adults', 'household_children'],
      dtype='object')

In [18]:
t=pd.read_csv('test_set_features.csv')

In [19]:
t=t[['xyz_concern', 'xyz_knowledge', 'behavioral_antiviral_meds',
       'behavioral_avoidance', 'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_outside_home', 'behavioral_touch_face',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'opinion_seas_vacc_effective', 'opinion_seas_risk',
       'opinion_seas_sick_from_vacc', 'age_group', 'race', 'sex',
       'household_adults', 'household_children']]

In [20]:
t

xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0              2.0            2.0                        0.0   
1              1.0            1.0                        0.0   
2              2.0            2.0                        0.0   
3              1.0            1.0                        0.0   
4              3.0            1.0                        1.0   
...            ...            ...                        ...   
26703          1.0            1.0                        0.0   
26704          3.0            1.0                        0.0   
26705          0.0            1.0                        0.0   
26706          3.0            1.0                        0.0   
26707          2.0            1.0                        0.0   

       behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                       1.0                   0.0                    1.0   
1                       0.0                   0.0                    0.0   
2                       0.0                   1.0                    1.0   
3                       0.0                   0.0                    0.0   
4                       1.0                   0.0                    1.0   
...                     ...                   ...                    ...   
26703                   1.0                   0.0                    1.0   
26704                   1.0                   0.0                    1.0   
26705                   0.0                   0.0                    0.0   
26706                   1.0                   0.0                    1.0   
26707                   0.0                   0.0                    1.0   

       behavioral_outside_home  behavioral_touch_face  chronic_med_condition  \
0                          0.0                    1.0                    0.0   
1                          0.0                    0.0                    0.0   
2                          1.0                    1.0                    0.0   
3                          0.0                    0.0                    1.0   
4                          1.0                    1.0                    0.0   
...                        ...                    ...                    ...   
26703                      0.0                    1.0                    0.0   
26704                      1.0                    1.0                    0.0   
26705                      0.0                    0.0                    0.0   
26706                      1.0                    0.0                    0.0   
26707                      0.0                    1.0                    0.0   

       child_under_6_months  health_worker  opinion_seas_vacc_effective  \
0                       0.0            0.0                          5.0   
1                       0.0            0.0                          4.0   
2                       0.0            0.0                          5.0   
3                       0.0            0.0                          4.0   
4                       0.0            1.0                          4.0   
...                     ...            ...                          ...   
26703                   0.0            0.0                          4.0   
26704                   0.0            1.0                          5.0   
26705                   0.0            0.0                          4.0   
26706                   1.0            0.0                          4.0   
26707                   0.0            0.0                          5.0   

       opinion_seas_risk  opinion_seas_sick_from_vacc      age_group  \
0                    1.0                          1.0  35 - 44 Years   
1                    1.0                          1.0  18 - 34 Years   
2                    4.0                          4.0  55 - 64 Years   
3                    4.0                          2.0      65+ Years   
4                    4.0                          2.0  35 - 44 Years   
...                  ...       

In [24]:
t.isnull().sum()

xyz_concern                    0
xyz_knowledge                  0
behavioral_antiviral_meds      0
behavioral_avoidance           0
behavioral_face_mask           0
behavioral_wash_hands          0
behavioral_outside_home        0
behavioral_touch_face          0
chronic_med_condition          0
child_under_6_months           0
health_worker                  0
opinion_seas_vacc_effective    0
opinion_seas_risk              0
opinion_seas_sick_from_vacc    0
age_group                      0
race                           0
sex                            0
household_adults               0
household_children             0
dtype: int64

In [23]:
for i in t.columns:
    if t[i].isnull().sum()>0:
        t[i].fillna(t[i].mode()[0],inplace=True)

In [25]:
for i in t.columns:
    if t[i].dtype=='float64':
        t[i]=t[i].astype(int)

In [28]:
def age_lab(i):
    if i=='65+ Years':
        return 5
    elif i=='55 - 64 Years':
        return 4
    elif i=='45 - 54 Years':
        return 3
    elif i=='18 - 34 Years':
        return 1
    else:
        return 2
def sex_lab(i):
    if i=='Female':
        return 1
    else:
        return 0
def race_lab(i):
    if i=='White':
        return 3
    elif i=='Black':
        return 2
    elif i=='Hispanic':
        return 1
    else:
        return 0
t['age_group']=t['age_group'].apply(age_lab)
t['race']=t['race'].apply(race_lab)
t['sex']=t['sex'].apply(sex_lab)

In [29]:
t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26708 entries, 0 to 26707
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   xyz_concern                  26708 non-null  int32
 1   xyz_knowledge                26708 non-null  int32
 2   behavioral_antiviral_meds    26708 non-null  int32
 3   behavioral_avoidance         26708 non-null  int32
 4   behavioral_face_mask         26708 non-null  int32
 5   behavioral_wash_hands        26708 non-null  int32
 6   behavioral_outside_home      26708 non-null  int32
 7   behavioral_touch_face        26708 non-null  int32
 8   chronic_med_condition        26708 non-null  int32
 9   child_under_6_months         26708 non-null  int32
 10  health_worker                26708 non-null  int32
 11  opinion_seas_vacc_effective  26708 non-null  int32
 12  opinion_seas_risk            26708 non-null  int32
 13  opinion_seas_sick_from_vacc  26708 non-null  i

In [33]:
svm=SVC(probability=True)
svm.fit(X_train, y_train)
    
# Predict probabilities for test set
y_pred_proba = svm.predict_proba(X_test)[:, 1]  # Probabilities of the positive class
    
# Example evaluation (replace with your own metrics)
print(f"\n Classification Report:")
y_pred = svm.predict(X_test)
print(classification_report(y_test, y_pred))
    
# Example of other metrics (accuracy, confusion matrix)
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\n---------------------------------------\n")


 Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.79      0.78      2683
           1       0.75      0.73      0.74      2305

    accuracy                           0.76      4988
   macro avg       0.76      0.76      0.76      4988
weighted avg       0.76      0.76      0.76      4988

Accuracy: 0.7636327185244587
Confusion Matrix:
[[2124  559]
 [ 620 1685]]

---------------------------------------



In [35]:
seasonal_proba=svm.predict_proba(t)[:, 1]

In [39]:
seasonal_proba

array([0.17562219, 0.12738004, 0.83642592, ..., 0.21997904, 0.48364457,
       0.76614944])

In [41]:
d1=pd.DataFrame({'seasonal_vaccine':seasonal_proba})

In [44]:
d1.to_csv('final_sub.csv',index=False)